[project]
name = "play"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mss>=10.0.0",
    "pyautogui>=0.9.54",
    "pynput>=1.8.1",
    "ultralytics>=8.3.135",
]

